[package]
name = "nmea2000"
version = "0.1.2"
edition = "2021"
description = "An NMEA 2000 library"
keywords = ["nmea2000", "n2k"]
categories = ["no-std", "embedded"]
license = "MIT"
repository = "https://github.com/akeamc/nmea2000"

[dependencies]
bytes = { version = "1.10.0", default-features = false }
generic-array = "1.2.0"
